### ISSUE TITLE
Updating introductory figures in the draft

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy-v1.0-paper#46]
As discussed in the call today, it might be better to organise some of the figures in the draft. Some proposals

1. Remove Figure 1 and add some of the relevant information in Figure 3
2. Remove Figure 2, and instead add the information in the text

It is useful to highlight that data can be read by gammapy at any stage - DL3, DL4, DL5 for further analysis. Thus, in Figure 3, probably showing input lines to the DL3 stage with IACT experiments, and at DL4 with HAWC/Fermi-LAT, and at DL5 with published catalogs/light curves/flux points can be useful. 

Comments @LauraOlivera @adonath @bkhelifi @registerrier ?

**Comment by LauraOlivera** [comment]
Thanks @AtreyeeS for starting this discussion. Some thoughts:

- I would support removing Figure 1 and adding the relevant takeaways from it to Figure 3.
- For this I would suggest to add a row on top of the current Figure 3 with something that represents gamma-ray instruments (in an ideal work this would not be names of specific instruments but some kind of schematic depiction of an IACT, a WCD and a satellite, but I can't make graphics so I won't be so demanding :smile: ). Below this block with instruments we could have an horizontal bar like the one at the bottom but with arrows at each step going down into DL3, DL4 and DL5, to signify that you can start the process at any of these stages.
- I am aware that my suggestion adds a new layer to an already complex figure. But I think it would result in a very nice, self-contained figure that will help people identify in one place the main components and uses of Gammapy.
- I would not be so strict in identifying DL3 with IACTs and DL4 with WCD/Fermi because event lists are DL3 and that could be confusing. I would rather have all instruments as a group linking to all the possible steps.
- I have no strong opinions about Figure 2. I would support keeping it or making it a paragraph instead. If we do keep it, I think it should be kept simple and neglect the dependencies between packages that don't include Gammapy.
