### ISSUE TITLE
Comments on Gammapy paper v1.0

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy-v1.0-paper#95]
**Version**
Compiled January 30.

**Note**
This is mainly typos and syntax suggestion. Also note that English is not my native language so even though I suggest typos or syntax corrections I might be wrong.
Hope this helps !

**Introduction** 
Line 8:
"both satellite as well as ground based instruments" 
-> I think we should say "both satellites and ground based instruments" 

Line 16:
"fews tens" -> "few tens"

Line 27-28:
"a very large FoV large duty-cycle" -> "a very large FoV and a large duty-cycle" or "a very large FoV, a large duty-cycle"

Line 32: 
"conducted by experiments operated by independent" 
-> "conducted through experiments operated by independent" to avoid the repetition of by

Line 42-43:
"in terms of the energy range covered, duty 42 cycle and spatial resolution."
-> Either put "the" for every item or don't put it at all, which I think is cleaner.

Line 99:
"common data format the GADF" -> either put a ":" or a "," after "GADF".

Line 103:
"Gammapy package is is built" -> "Gammapy package is built"

Line 104-106:
Why is iminuit not quoted as the gammapy minimiser ?

Line 115:
"based n the GADF" -> "based on the GADF"

**Gamma-ray Data Analysis**
Line 179:
"In general, they depend" -> I would say "In general, these IRFs depend" or "In general, IRFs depend" to clarify what they refers to.

Line 181-182:
-> The last sentence is not very clear to me.

Line 212:
"After all data has been projected" -> "After all data have been projected" 

**Gammapy Package**
Line 303-304:
"as well as FITS HDU index file" -> "as well as a FITS HDU index file"

Line 361:
"on true energy of offset form" -> "on true energy and offset from"

Line 390-396:
This sentence is very long and very complex.

Line 411:
The top of the line is cut (maybe it's only on my side).

Line 510-511:
"The end product of the data reduction process are a set" 
either "The end products of the data reduction process are a set" or The end product of the data reduction process is a set"
I think the later is the correct one since it is "a set".

Line 558:
"The code example ??" -> I guess this is a known issue ?

Line 570:
"To simplify the the definition" -> "To simplify the definition"

Line 597-598:
"spatial models are all normalized such as they integrate" -> isn't it "such that" ?

Line 662-663:
"From 662 the TS value the significance" -> I would put a "," after "value"

Line 729-730:
"specific colormaps for false color image representation" -> Is it relevant to specify "false colour" ? since it will always be false colour in gamma astronomy.

Line 763:
"enriched with time with by users" -> "enriched with time by users"

**Applications**
Line 948:
"Thye consist of" -> "They consist of"

Line 955:
"They data reduction" -> "The data reduction"

Line 1070:
"This an e.g. easily" -> I guess it is "This can". However I don't know if I would put 'e.g.'.

Line 1079:
"our analyses strategies" -> Isn't it "analysis strategies"?

Line 1080-1081:
"to process the large datasets provided by the surveys." ->  I would remove the "the " : "to process large datasets provided by surveys."

**Comment by adonath** [comment]
Thanks a lot for the comments @MRegeard!

**Comment by adonath** [comment]
## Introduction
> Line 8:
"both satellite as well as ground based instruments"
-> I think we should say "both satellites and ground based instruments"

Decided to remove "both" instead...


> Line 16:
"fews tens" -> "few tens"

Fixed

> Line 27-28:
"a very large FoV large duty-cycle" -> "a very large FoV and a large duty-cycle" or "a very large FoV, a large duty-cycle"

Fixed

> Line 32:
"conducted by experiments operated by independent"
-> "conducted through experiments operated by independent" to avoid the repetition of by

Fixed

> Line 42-43:
"in terms of the energy range covered, duty 42 cycle and spatial resolution."
-> Either put "the" for every item or don't put it at all, which I think is cleaner.

Removed "the"

> Line 99:
"common data format the GADF" -> either put a ":" or a "," after "GADF".

Rephrased to:  "Various \gammaray instruments
export their data to the standardised common \gadf data format."

> Line 103:
"Gammapy package is is built" -> "Gammapy package is built"

Fixed

> Line 104-106:
Why is iminuit not quoted as the gammapy minimiser ?

Fixed.

> Line 115:
"based n the GADF" -> "based on the GADF"

Fixed

## Gamma-ray Data Analysis

> Line 179:
"In general, they depend" -> I would say "In general, these IRFs depend" or "In general, IRFs depend" to clarify what they refers to.

Fixed.

> Line 181-182:
-> The last sentence is not very clear to me.

Changed to: "In general, IRFs depend on the geometrical parameters of the detector, e.g. location 
of an event in the FoV or the elevation angle of the event. So IRFs might be parametrised
as a function of such detector specific coordinates too."

> Line 212:
"After all data has been projected" -> "After all data have been projected"

 Fixed.

## Gammapy Package
> Line 303-304:
"as well as FITS HDU index file" -> "as well as a FITS HDU index file"

Fixed.

> Line 361:
"on true energy of offset form" -> "on true energy and offset from"

Fixed.

> Line 390-396:
This sentence is very long and very complex.

Changed to: "The instrumental background rate can be represented as either a 2-dimensional
data structure named \code{Background2D} or a 3-dimensional one named \code{Background3D}.
The background rate is stored as a differential count rate, normalised per solid angle
and energy at different reconstructed energies. In the first case the background is
expected to follow a radially symmetric shape and changes only with the offset angle from
FoV center. In the other case the background is allowed to vary with 
longitude and latitude of a tangential FoV coordinates system."

> Line 411:
The top of the line is cut (maybe it's only on my side).

Looks fine to me. No change.

> Line 510-511:
"The end product of the data reduction process are a set"
either "The end products of the data reduction process are a set" or The end product of the data reduction process is a set"
I think the later is the correct one since it is "a set".

Fixed.

> Line 558:
"The code example ??" -> I guess this is a known issue ?

Fixed

> Line 570:
"To simplify the the definition" -> "To simplify the definition"

Fixed

> Line 597-598:
"spatial models are all normalized such as they integrate" -> isn't it "such that" ?

Fixed

> Line 662-663:
"From 662 the TS value the significance" -> I would put a "," after "value"

Fixed 

> Line 729-730:
"specific colormaps for false color image representation" -> Is it relevant to specify "false colour" ? since it will always be false colour in gamma astronomy.

Fixed

> Line 763:
"enriched with time with by users" -> "enriched with time by users"

Fixed

## Applications
> Line 948:
"Thye consist of" -> "They consist of"

Fixed

> Line 955:
"They data reduction" -> "The data reduction"

Fixed

> Line 1070:
"This an e.g. easily" -> I guess it is "This can". However I don't know if I would put 'e.g.'.

Fixed, removed "e.g."

> Line 1079:
"our analyses strategies" -> Isn't it "analysis strategies"?

Fixed

> Line 1080-1081:
"to process the large datasets provided by the surveys." -> I would remove the "the " : "to process large datasets provided by surveys.

Fixed
